//
// Created by Jeka8833 on 22.01.2023.
//

#ifndef POWERWRITER_SETTINGS_H
#define POWERWRITER_SETTINGS_H

#endif //POWERWRITER_SETTINGS_H

#define CS_PIN_SD 4
#define DISPLAY_ADDRESS 0x27
#define DISPLAY_COLUMN 16
#define DISPLAY_ROW 2
#define DISPLAY_BRIGHTNESS_PWM 10

#define LIGHT_SENSOR 3

#define BUTTONS_PIN 2

#define BUTTON_RIGHT 301
#define BUTTON_CENTER 722
#define BUTTON_LEFT 1023